// Fill out your copyright notice in the Description page of Project Settings.

#include "CityUI.h"
#include "Components/TextBlock.h"
#include "Components/Image.h"
#include "Components/ProgressBar.h"
#include "Components/Button.h"
#include "Components/Border.h"
#include "../../SuperGameInstance.h"
#include "../../SuperPlayerState.h"
#include "../../WorldComponent.h"

void UCityUI::NativeConstruct()
{
	Super::NativeConstruct();

	// мҙҲкё° н…ҚмҠӨнҠё м„Өм •
	if (ScienceTxt)
	{
		ScienceTxt->SetText(FText::FromString(TEXT("+0")));
	}

	if (FaithTxt)
	{
		FaithTxt->SetText(FText::FromString(TEXT("+0")));
	}

	if (GoldTxt)
	{
		GoldTxt->SetText(FText::FromString(TEXT("+0")));
	}

	if (ProductionTxt)
	{
		ProductionTxt->SetText(FText::FromString(TEXT("+0")));
	}

	if (FoodTxt)
	{
		FoodTxt->SetText(FText::FromString(TEXT("+0")));
	}

	// ProductionWidлҠ” кё°ліём ҒмңјлЎң Visible, PurchaseWidлҠ” Hidden
	if (ProductionWid)
	{
		ProductionWid->SetVisibility(ESlateVisibility::Visible);
	}

	if (PurchaseWid)
	{
		PurchaseWid->SetVisibility(ESlateVisibility::Hidden);
	}

	// лІ„нҠј нҒҙлҰӯ мқҙлІӨнҠё л°”мқёл”©
	if (ProductionBtn)
	{
		ProductionBtn->OnClicked.AddDynamic(this, &UCityUI::OnProductionBtnClicked);
	}

	if (PurchaseBtn)
	{
		PurchaseBtn->OnClicked.AddDynamic(this, &UCityUI::OnPurchaseBtnClicked);
	}
}

void UCityUI::UpdateCityData()
{
	// GetGameInstance -> CastToSuperGameInstance -> GetPlayerState(0)
	if (!GetWorld())
	{
		return;
	}

	USuperGameInstance* SuperGameInst = Cast<USuperGameInstance>(GetWorld()->GetGameInstance());
	if (!SuperGameInst)
	{
		return;
	}

	ASuperPlayerState* PlayerState = SuperGameInst->GetPlayerState(0);
	if (!PlayerState)
	{
		return;
	}

	UWorldComponent* WorldComponent = SuperGameInst->GetGeneratedWorldComponent();
	if (!WorldComponent)
	{
		return;
	}

	// CalculateTotalScienceYieldлҘј +x нҳ•мӢқмңјлЎң ScienceTxtм—җ н‘ңмӢң
	if (ScienceTxt)
	{
		int32 ScienceYield = PlayerState->CalculateTotalScienceYield(WorldComponent);
		FString ScienceString = FString::Printf(TEXT("+%d"), ScienceYield);
		ScienceTxt->SetText(FText::FromString(ScienceString));
	}

	// CalculateTotalFaithYieldлҘј +x нҳ•мӢқмңјлЎң FaithTxtм—җ н‘ңмӢң
	if (FaithTxt)
	{
		int32 FaithYield = PlayerState->CalculateTotalFaithYield(WorldComponent);
		FString FaithString = FString::Printf(TEXT("+%d"), FaithYield);
		FaithTxt->SetText(FText::FromString(FaithString));
	}

	// CalculateTotalGoldYieldлҘј +x нҳ•мӢқмңјлЎң GoldTxtм—җ н‘ңмӢң
	if (GoldTxt)
	{
		int32 GoldYield = PlayerState->CalculateTotalGoldYield(WorldComponent);
		FString GoldString = FString::Printf(TEXT("+%d"), GoldYield);
		GoldTxt->SetText(FText::FromString(GoldString));
	}

	// CalculateTotalProductionYieldлҘј +x нҳ•мӢқмңјлЎң ProductionTxtм—җ н‘ңмӢң
	if (ProductionTxt)
	{
		int32 ProductionYield = PlayerState->CalculateTotalProductionYield(WorldComponent);
		FString ProductionString = FString::Printf(TEXT("+%d"), ProductionYield);
		ProductionTxt->SetText(FText::FromString(ProductionString));
	}

	// CalculateTotalFoodYieldлҘј +x нҳ•мӢқмңјлЎң FoodTxtм—җ н‘ңмӢң
	if (FoodTxt)
	{
		int32 FoodYield = PlayerState->CalculateTotalFoodYield(WorldComponent);
		FString FoodString = FString::Printf(TEXT("+%d"), FoodYield);
		FoodTxt->SetText(FText::FromString(FoodString));
	}
}

void UCityUI::OnProductionBtnClicked()
{
	// ProductionBtn нҒҙлҰӯ мӢң ProductionWidлҘј Visible, PurchaseWidлҘј HiddenмңјлЎң м„Өм •
	if (ProductionWid)
	{
		ProductionWid->SetVisibility(ESlateVisibility::Visible);
	}

	if (PurchaseWid)
	{
		PurchaseWid->SetVisibility(ESlateVisibility::Hidden);
	}
}

void UCityUI::OnPurchaseBtnClicked()
{
	// PurchaseBtn нҒҙлҰӯ мӢң PurchaseWidлҘј Visible, ProductionWidлҘј HiddenмңјлЎң м„Өм •
	if (PurchaseWid)
	{
		PurchaseWid->SetVisibility(ESlateVisibility::Visible);
	}

	if (ProductionWid)
	{
		ProductionWid->SetVisibility(ESlateVisibility::Hidden);
	}
}

