// Fill out your copyright notice in the Description page of Project Settings.

#include "WorldSpawner.h"
#include "../SuperGameInstance.h"
#include "../Unit/UnitManager.h"
#include "../Facility/FacilityManager.h"
#include "../City/CityActor.h"
#include "../SuperPlayerState.h"
#include "../City/CityComponent.h"
#include "../Research/ResearchComponent.h"
#include "../SuperCameraPawn.h"
#include "../SuperGameController.h"
#include "Engine/World.h"
#include "Kismet/GameplayStatics.h"

AWorldSpawner::AWorldSpawner()
{
	PrimaryActorTick.bCanEverTick = false;

	WorldComponent = nullptr;
	TileActorClass = AWorldTileActor::StaticClass();
	bIsSpawning = false;
	CurrentSpawnIndex = 0;
}

void AWorldSpawner::BeginPlay()
{
	Super::BeginPlay();
	
		// GameInstanceм—җм„ң WorldComponent к°Җм ёмҳӨкё° л°Ҹ UnitManager, FacilityManager мғқм„ұ
		if (UWorld* World = GetWorld())
		{
			if (USuperGameInstance* SuperGameInst = Cast<USuperGameInstance>(World->GetGameInstance()))
			{
				WorldComponent = SuperGameInst->GetGeneratedWorldComponent();
				
				// UnitManager мғқм„ұ л°Ҹ м„Өм •
				if (WorldComponent)
				{
					UUnitManager* UnitManager = NewObject<UUnitManager>(this);
					if (UnitManager)
					{
						UnitManager->SetWorldComponent(WorldComponent);
						SuperGameInst->SetUnitManager(UnitManager);
					}
					
					// FacilityManager мғқм„ұ л°Ҹ м„Өм •
					UFacilityManager* FacilityManager = NewObject<UFacilityManager>(this);
					if (FacilityManager)
					{
						// лҚ°мқҙн„° н…Ңмқҙлё” лЎңл“ң (BeginPlayк°Җ нҳём¶ңлҗҳм§Җ м•Ҡмқ„ мҲҳ мһҲмңјлҜҖлЎң м§Ғм ‘ нҳём¶ң)
						FacilityManager->LoadFacilityDataTable();
						SuperGameInst->SetFacilityManager(FacilityManager);
						
						// мӢңм„Ө ліҖкІҪ лҚёлҰ¬кІҢмқҙнҠё кө¬лҸ… (мһҗмӣҗ л©”мӢң м ңм–ҙмҡ©)
						FacilityManager->OnFacilityChanged.AddDynamic(this, &AWorldSpawner::OnFacilityChanged);
					}
				}
				
				// LoadingTilesUIм—җм„ң SpawnAllTiles()лҘј нҳём¶ңн•  л•Ңк№Ңм§Җ лҢҖкё°
				// мһҗлҸҷ мҠӨнҸ° м ңкұ° - LoadingTilesUIк°Җ м ңм–ҙ
			}
		}
}

void AWorldSpawner::SpawnAllTiles()
{
	if (!WorldComponent)
	{
		return;
	}

	if (bIsSpawning)
	{
		return;
	}

	// кё°мЎҙ нғҖмқјл“Ө м ңкұ°
	ClearAllTiles();

	// лӘЁл“  нғҖмқј к°Җм ёмҳӨкё°
	TArray<UWorldTile*> AllTiles = WorldComponent->GetAllTiles();
	if (AllTiles.Num() == 0)
	{
		OnTileSpawnCompleted.Broadcast();
		return;
	}

	// л№„лҸҷкё° мҠӨнҸ° мӨҖл№„
	bIsSpawning = true;
	TilesToSpawn = AllTiles;
	CurrentSpawnIndex = 0;

	// нғҖмқҙлЁёлЎң л№„лҸҷкё° мҠӨнҸ° мӢңмһ‘ (л§Ө н”„л Ҳмһ„ м—¬лҹ¬ к°ңм”© мҠӨнҸ°)
	GetWorld()->GetTimerManager().SetTimer(
		SpawnTimerHandle,
		this,
		&AWorldSpawner::ProcessAsyncSpawn,
		0.016f, // ~60fps
		true
	);
}

void AWorldSpawner::ProcessAsyncSpawn()
{
	if (!bIsSpawning || CurrentSpawnIndex >= TilesToSpawn.Num())
	{
		// мҠӨнҸ° мҷ„лЈҢ
		bIsSpawning = false;
		GetWorld()->GetTimerManager().ClearTimer(SpawnTimerHandle);
		
		OnTileSpawnCompleted.Broadcast();
		return;
	}

	// н•ң н”„л Ҳмһ„м—җ м—¬лҹ¬ к°ң мҠӨнҸ° (м„ұлҠҘ мЎ°м Ҳ к°ҖлҠҘ)
	int32 SpawnPerFrame = 50; // н”„л Ҳмһ„лӢ№ 50к°ңм”© мҠӨнҸ°
	int32 SpawnCount = 0;

	while (CurrentSpawnIndex < TilesToSpawn.Num() && SpawnCount < SpawnPerFrame)
	{
		UWorldTile* TileData = TilesToSpawn[CurrentSpawnIndex];
		if (TileData)
		{
			SpawnTileActor(TileData);
		}

		CurrentSpawnIndex++;
		SpawnCount++;
	}
}

AWorldTileActor* AWorldSpawner::SpawnTileActor(UWorldTile* TileData)
{
	if (!TileData || !GetWorld())
	{
		return nullptr;
	}

	// мҠӨнҸ° нҢҢлқјлҜён„° м„Өм •
	FActorSpawnParameters SpawnParams;
	SpawnParams.Owner = this;
	SpawnParams.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;

	// нғҖмқј м•Ўн„° мҠӨнҸ°
	FVector SpawnLocation = TileData->GetWorldPosition();
	FRotator SpawnRotation = FRotator::ZeroRotator;

	AWorldTileActor* TileActor = GetWorld()->SpawnActor<AWorldTileActor>(
		TileActorClass,
		SpawnLocation,
		SpawnRotation,
		SpawnParams
	);

	if (TileActor)
	{
		// нғҖмқј лҚ°мқҙн„° м„Өм •
		TileActor->SetTileData(TileData);

		// л§өм—җ м¶”к°Җ
		FVector2D HexPos = TileData->GetGridPosition();
		TileActors.Add(HexPos, TileActor);
	}

	return TileActor;
}

void AWorldSpawner::UpdateTileVisual(FVector2D HexPosition)
{
	if (AWorldTileActor* TileActor = GetTileActorAtHex(HexPosition))
	{
		TileActor->UpdateVisual();
	}
}

AWorldTileActor* AWorldSpawner::GetTileActorAtHex(FVector2D HexPosition) const
{
	if (AWorldTileActor* const* FoundActor = TileActors.Find(HexPosition))
	{
		return *FoundActor;
	}
	return nullptr;
}

void AWorldSpawner::ClearAllTiles()
{
	// лӘЁл“  нғҖмқј м•Ўн„° нҢҢкҙҙ
	for (auto& Pair : TileActors)
	{
		if (Pair.Value)
		{
			Pair.Value->Destroy();
		}
	}

	TileActors.Empty();
}

void AWorldSpawner::SpawnAllCities()
{
	if (!WorldComponent)
	{
		return;
	}

	// кё°мЎҙ лҸ„мӢң м ңкұ°
	ClearAllCities();

	TArray<FVector2D> CityHexes = WorldComponent->GetStartingCityHexes();
	for (const FVector2D& Hex : CityHexes)
	{
		SpawnCityActorAtHex(Hex);
	}
}

ACityActor* AWorldSpawner::SpawnCityActorAtHex(FVector2D Hex)
{
	if (!WorldComponent || !GetWorld())
	{
		return nullptr;
	}

	if (!CityActorClass)
	{
		CityActorClass = ACityActor::StaticClass();
	}

	FVector SpawnLocation = WorldComponent->HexToWorld(Hex);

	// м§Җнҳ• нғҖмһ…м—җ л”°лқј Z мҳӨн”„м…Ӣ м Ғмҡ©
	if (UWorldTile* Tile = WorldComponent->GetTileAtHex(Hex))
	{
		float ZOffset = 73.0f; // Plains кё°ліёк°’
		ELandType LandType = Tile->GetLandType();
		if (LandType == ELandType::Hills)
		{
			ZOffset = 146.0f;
		}
		else if (LandType == ELandType::Mountains)
		{
			ZOffset = 219.0f;
		}
		SpawnLocation.Z += ZOffset;
	}
	FRotator SpawnRotation = FRotator::ZeroRotator;

	FActorSpawnParameters SpawnParams;
	SpawnParams.Owner = this;
	SpawnParams.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;

	ACityActor* City = GetWorld()->SpawnActor<ACityActor>(CityActorClass, SpawnLocation, SpawnRotation, SpawnParams);
	if (City)
	{
		CityActors.Add(Hex, City);
	}
	return City;
}

ACityActor* AWorldSpawner::GetCityActorAtHex(FVector2D Hex) const
{
	if (ACityActor* const* Found = CityActors.Find(Hex))
	{
		return *Found;
	}
	return nullptr;
}

void AWorldSpawner::ClearAllCities()
{
	for (auto& Pair : CityActors)
	{
		if (Pair.Value)
		{
			Pair.Value->Destroy();
		}
	}
	CityActors.Empty();
}

void AWorldSpawner::AssignCitiesToPlayers()
{
	// GameInstanceм—җм„ң PlayerStates к°Җм ёмҳӨкё°
	USuperGameInstance* GameInstance = nullptr;
	if (UWorld* World = GetWorld())
	{
		GameInstance = Cast<USuperGameInstance>(World->GetGameInstance());
	}
	
	if (!GameInstance || !WorldComponent)
	{
		return;
	}
	
	// лҸ„мӢң мўҢн‘ң к°Җм ёмҳӨкё°
	TArray<FVector2D> CityHexes = WorldComponent->GetStartingCityHexes();
	
	// к°Ғ н”Ңл Ҳмқҙм–ҙм—җкІҢ лҸ„мӢң л°°м • (мҲңм„ңлҢҖлЎң)
	for (int32 i = 0; i < CityHexes.Num(); i++)
	{
		// CityActor к°Җм ёмҳӨкё°
		ACityActor* City = GetCityActorAtHex(CityHexes[i]);
		if (!City)
		{
			continue;
		}
		
		// PlayerState к°Җм ёмҳӨкё°
		ASuperPlayerState* PlayerState = GameInstance->GetPlayerState(i);
		if (!PlayerState)
		{
			continue;
		}
		
		// лҸ„мӢң м»ҙнҸ¬л„ҢнҠё мғқм„ұ л°Ҹ л°°м •
		UCityComponent* CityComponent = NewObject<UCityComponent>(PlayerState);
		if (CityComponent)
		{
			PlayerState->SetCityComponent(CityComponent);
		}
		
		PlayerState->SetCityCoordinate(CityHexes[i]);
		
		// кё°мҲ  м»ҙнҸ¬л„ҢнҠё мғқм„ұ л°Ҹ л°°м •
		UResearchComponent* ResearchComponent = NewObject<UResearchComponent>(PlayerState);
		if (ResearchComponent)
		{
			PlayerState->SetResearchComponent(ResearchComponent);
		}
		
		// лҸ„мӢң мӨ‘мӢ¬ л°ҳкІҪ 1м№ёмқҳ нғҖмқјл“Өмқ„ мҶҢмң лЎң м„Өм • (мҙҲкё° лҸ„мӢң мҳҒм—ӯ)
		TArray<FVector2D> InitialTiles = WorldComponent->GetHexesInRadius(CityHexes[i], 1);
		for (const FVector2D& TileCoord : InitialTiles)
		{
			PlayerState->AddOwnedTile(TileCoord, WorldComponent);
		}
	}
	
	// лҸ„мӢң л°°м • мҷ„лЈҢ нӣ„ м№ҙл©”лқјлҘј н”Ңл Ҳмқҙм–ҙ 0мқҳ лҸ„мӢңлЎң мқҙлҸҷ
	MoveCameraToPlayerCity();
}

void AWorldSpawner::MoveCameraToPlayerCity()
{
	if (!GetWorld() || !WorldComponent)
	{
		return;
	}
	
	// GameInstanceм—җм„ң н”Ңл Ҳмқҙм–ҙ 0мқҳ PlayerState к°Җм ёмҳӨкё°
	if (USuperGameInstance* GameInstance = Cast<USuperGameInstance>(GetWorld()->GetGameInstance()))
	{
		if (ASuperPlayerState* PlayerState0 = GameInstance->GetPlayerState(0))
		{
			// н”Ңл Ҳмқҙм–ҙ 0мқҙ лҸ„мӢңлҘј к°Җм§Җкі  мһҲлҠ”м§Җ нҷ•мқё
			if (PlayerState0->HasCity())
			{
				// лҸ„мӢң мўҢн‘ң к°Җм ёмҳӨкё°
				FVector2D CityHex = PlayerState0->GetCityCoordinate();
				
				// Hex мўҢн‘ңлҘј World мўҢн‘ңлЎң ліҖнҷҳ
				FVector CityWorldPos = WorldComponent->HexToWorld(CityHex);
				
				// PlayerControllerлҘј нҶөн•ҙ м№ҙл©”лқј Pawn к°Җм ёмҳӨкё°
				if (APlayerController* PC = GetWorld()->GetFirstPlayerController())
				{
					if (ASuperCameraPawn* CameraPawn = Cast<ASuperCameraPawn>(PC->GetPawn()))
					{
						// нҳ„мһ¬ м№ҙл©”лқјмқҳ Z мўҢн‘ң мң м§Җ (лҶ’мқҙлҠ” к·ёлҢҖлЎң)
						FVector CurrentLocation = CameraPawn->GetActorLocation();
						CityWorldPos.Z = CurrentLocation.Z;
						
						// м№ҙл©”лқј мң„м№ҳ м„Өм •
						CameraPawn->SetActorLocation(CityWorldPos);
					}
				}
			}
		}
	}
}

void AWorldSpawner::OnFacilityChanged(FVector2D TileCoordinate)
{
	// н•ҙлӢ№ нғҖмқјмқҳ WorldTileActor м°ҫкё°
	if (AWorldTileActor* TileActor = GetTileActorAtHex(TileCoordinate))
	{
		// FacilityManagerлҘј нҶөн•ҙ н•ҙлӢ№ нғҖмқјм—җ мӢңм„Өмқҙ мһҲлҠ”м§Җ нҷ•мқё
		if (UWorld* World = GetWorld())
		{
			if (USuperGameInstance* SuperGameInst = Cast<USuperGameInstance>(World->GetGameInstance()))
			{
				if (UFacilityManager* FacilityManager = SuperGameInst->GetFacilityManager())
				{
					if (FacilityManager->HasFacilityAtTile(TileCoordinate))
					{
						// мӢңм„Өмқҙ мһҲмңјл©ҙ мһҗмӣҗ л©”мӢң мҲЁкё°кё°
						TileActor->SetResourceVisibility(false);
					}
					else
					{
						// мӢңм„Өмқҙ м—Ҷмңјл©ҙ мһҗмӣҗ л©”мӢң лӢӨмӢң ліҙмқҙкё°
						TileActor->UpdateVisual();
					}
				}
			}
		}
	}
}

