// Fill out your copyright notice in the Description page of Project Settings.

#include "CityUI.h"
#include "Components/TextBlock.h"
#include "Components/Image.h"
#include "Components/ProgressBar.h"
#include "Components/Button.h"
#include "Components/Border.h"
#include "../../SuperGameInstance.h"
#include "../../SuperPlayerState.h"
#include "../../World/WorldComponent.h"
#include "../../City/CityComponent.h"
#include "../../City/CityStruct.h"
#include "../../Status/UnitStatusStruct.h"

void UCityUI::NativeConstruct()
{
	Super::NativeConstruct();

	// мҙҲкё° н…ҚмҠӨнҠё м„Өм •
	if (ScienceTxt)
	{
		ScienceTxt->SetText(FText::FromString(TEXT("+0")));
	}

	if (FaithTxt)
	{
		FaithTxt->SetText(FText::FromString(TEXT("+0")));
	}

	if (GoldTxt)
	{
		GoldTxt->SetText(FText::FromString(TEXT("+0")));
	}

	if (ProductionTxt)
	{
		ProductionTxt->SetText(FText::FromString(TEXT("+0")));
	}

	if (FoodTxt)
	{
		FoodTxt->SetText(FText::FromString(TEXT("+0")));
	}

	// ProductionWidлҠ” кё°ліём ҒмңјлЎң Visible, PurchaseWidлҠ” Hidden
	if (ProductionWid)
	{
		ProductionWid->SetVisibility(ESlateVisibility::Visible);
	}

	if (PurchaseWid)
	{
		PurchaseWid->SetVisibility(ESlateVisibility::Hidden);
	}

	// лІ„нҠј нҒҙлҰӯ мқҙлІӨнҠё л°”мқёл”©
	if (ProductionBtn)
	{
		ProductionBtn->OnClicked.AddDynamic(this, &UCityUI::OnProductionBtnClicked);
	}

	if (PurchaseBtn)
	{
		PurchaseBtn->OnClicked.AddDynamic(this, &UCityUI::OnPurchaseBtnClicked);
	}

	// лҸ„мӢң м»ҙнҸ¬л„ҢнҠё м°ёмЎ° к°Җм ёмҳӨкё° л°Ҹ лҚёлҰ¬кІҢмқҙнҠё л°”мқёл”©
	BindToProductionDelegates();
}

void UCityUI::UpdateCityData()
{
	// GetGameInstance -> CastToSuperGameInstance -> GetPlayerState(0)
	if (!GetWorld())
	{
		return;
	}

	USuperGameInstance* SuperGameInst = Cast<USuperGameInstance>(GetWorld()->GetGameInstance());
	if (!SuperGameInst)
	{
		return;
	}

	ASuperPlayerState* PlayerState = SuperGameInst->GetPlayerState(0);
	if (!PlayerState)
	{
		return;
	}

	UWorldComponent* WorldComponent = SuperGameInst->GetGeneratedWorldComponent();
	if (!WorldComponent)
	{
		return;
	}

	// CalculateTotalScienceYieldлҘј +x нҳ•мӢқмңјлЎң ScienceTxtм—җ н‘ңмӢң
	if (ScienceTxt)
	{
		int32 ScienceYield = PlayerState->CalculateTotalScienceYield(WorldComponent);
		FString ScienceString = FString::Printf(TEXT("+%d"), ScienceYield);
		ScienceTxt->SetText(FText::FromString(ScienceString));
	}

	// CalculateTotalFaithYieldлҘј +x нҳ•мӢқмңјлЎң FaithTxtм—җ н‘ңмӢң
	if (FaithTxt)
	{
		int32 FaithYield = PlayerState->CalculateTotalFaithYield(WorldComponent);
		FString FaithString = FString::Printf(TEXT("+%d"), FaithYield);
		FaithTxt->SetText(FText::FromString(FaithString));
	}

	// CalculateTotalGoldYieldлҘј +x нҳ•мӢқмңјлЎң GoldTxtм—җ н‘ңмӢң
	if (GoldTxt)
	{
		int32 GoldYield = PlayerState->CalculateTotalGoldYield(WorldComponent);
		FString GoldString = FString::Printf(TEXT("+%d"), GoldYield);
		GoldTxt->SetText(FText::FromString(GoldString));
	}

	// CalculateTotalProductionYieldлҘј +x нҳ•мӢқмңјлЎң ProductionTxtм—җ н‘ңмӢң
	if (ProductionTxt)
	{
		int32 ProductionYield = PlayerState->CalculateTotalProductionYield(WorldComponent);
		FString ProductionString = FString::Printf(TEXT("+%d"), ProductionYield);
		ProductionTxt->SetText(FText::FromString(ProductionString));
	}

	// CalculateTotalFoodYieldлҘј +x нҳ•мӢқмңјлЎң FoodTxtм—җ н‘ңмӢң
	if (FoodTxt)
	{
		int32 FoodYield = PlayerState->CalculateTotalFoodYield(WorldComponent);
		FString FoodString = FString::Printf(TEXT("+%d"), FoodYield);
		FoodTxt->SetText(FText::FromString(FoodString));
	}

	// мғқмӮ° м •ліҙ м—…лҚ°мқҙнҠё
	UpdateProductionInfo();
}

void UCityUI::OnProductionBtnClicked()
{
	// ProductionBtn нҒҙлҰӯ мӢң ProductionWidлҘј Visible, PurchaseWidлҘј HiddenмңјлЎң м„Өм •
	if (ProductionWid)
	{
		ProductionWid->SetVisibility(ESlateVisibility::Visible);
	}

	if (PurchaseWid)
	{
		PurchaseWid->SetVisibility(ESlateVisibility::Hidden);
	}
}

void UCityUI::OnPurchaseBtnClicked()
{
	// PurchaseBtn нҒҙлҰӯ мӢң PurchaseWidлҘј Visible, ProductionWidлҘј HiddenмңјлЎң м„Өм •
	if (PurchaseWid)
	{
		PurchaseWid->SetVisibility(ESlateVisibility::Visible);
	}

	if (ProductionWid)
	{
		ProductionWid->SetVisibility(ESlateVisibility::Hidden);
	}
}

void UCityUI::NativeDestruct()
{
	// лҚёлҰ¬кІҢмқҙнҠё л°”мқёл”© н•ҙм ң
	UnbindFromProductionDelegates();

	Super::NativeDestruct();
}

void UCityUI::BindToProductionDelegates()
{
	if (!GetWorld())
	{
		return;
	}

	USuperGameInstance* SuperGameInst = Cast<USuperGameInstance>(GetWorld()->GetGameInstance());
	if (!SuperGameInst)
	{
		return;
	}

	ASuperPlayerState* PlayerState = SuperGameInst->GetPlayerState(0);
	if (!PlayerState)
	{
		return;
	}

	// CityComponent к°Җм ёмҳӨкё°
	CachedCityComponent = PlayerState->GetCityComponent();
	if (!CachedCityComponent)
	{
		return;
	}

	// кё°мЎҙ л°”мқёл”© н•ҙм ң нӣ„ мғҲлЎң л°”мқёл”©
	UnbindFromProductionDelegates();

	// мғқмӮ° мӢңмһ‘ лҚёлҰ¬кІҢмқҙнҠё л°”мқёл”©
	CachedCityComponent->OnProductionStarted.AddDynamic(this, &UCityUI::OnProductionStarted);

	// мғқмӮ° мҷ„лЈҢ лҚёлҰ¬кІҢмқҙнҠё л°”мқёл”©
	CachedCityComponent->OnProductionCompleted.AddDynamic(this, &UCityUI::OnProductionCompleted);

	// мғқмӮ° м§„н–үлҸ„ ліҖкІҪ лҚёлҰ¬кІҢмқҙнҠё л°”мқёл”©
	CachedCityComponent->OnProductionProgressChanged.AddDynamic(this, &UCityUI::OnProductionProgressChanged);

	// мҙҲкё° мғқмӮ° м •ліҙ м—…лҚ°мқҙнҠё
	UpdateProductionInfo();
}

void UCityUI::UnbindFromProductionDelegates()
{
	if (CachedCityComponent)
	{
		// лҚёлҰ¬кІҢмқҙнҠё л°”мқёл”© н•ҙм ң
		CachedCityComponent->OnProductionStarted.RemoveDynamic(this, &UCityUI::OnProductionStarted);
		CachedCityComponent->OnProductionCompleted.RemoveDynamic(this, &UCityUI::OnProductionCompleted);
		CachedCityComponent->OnProductionProgressChanged.RemoveDynamic(this, &UCityUI::OnProductionProgressChanged);
	}
}

void UCityUI::OnProductionStarted(FName ProductionID)
{
	// мғқмӮ° мӢңмһ‘ мӢң мғқмӮ° м •ліҙ м—…лҚ°мқҙнҠё
	UpdateProductionInfo();
}

void UCityUI::OnProductionCompleted(FName ProductionID)
{
	// лҸ„мӢң лҚ°мқҙн„° м—…лҚ°мқҙнҠё (кұҙл¬ј м¶”к°ҖлЎң мқён•ң мғқмӮ°лҹү ліҖнҷ” л°ҳмҳҒ)
	UpdateCityData();
}

void UCityUI::OnProductionProgressChanged()
{
	// мғқмӮ° м§„н–үлҸ„ ліҖкІҪ мӢң мғқмӮ° м •ліҙ м—…лҚ°мқҙнҠё (м§„н–үлҸ„ л°” нҸ¬н•Ё)
	UpdateProductionInfo();
}

void UCityUI::UpdateProductionInfo()
{
	if (!CachedCityComponent)
	{
		// CityComponentк°Җ м—Ҷмңјл©ҙ мҙҲкё°нҷ” мӢңлҸ„
		BindToProductionDelegates();
		if (!CachedCityComponent)
		{
			// м—¬м „нһҲ м—Ҷмңјл©ҙ мғқмӮ° м •ліҙ мҙҲкё°нҷ”
			if (ProducingTxt)
			{
				ProducingTxt->SetText(FText::GetEmpty());
			}
			if (ProducingImg)
			{
				ProducingImg->SetBrushFromTexture(nullptr);
			}
			if (ProducingBar)
			{
				ProducingBar->SetPercent(0.0f);
			}
			return;
		}
	}

	// нҳ„мһ¬ мғқмӮ° мғҒнғң к°Җм ёмҳӨкё°
	FCityCurrentStat CurrentStat = CachedCityComponent->GetCurrentStat();

	// мғқмӮ° мӨ‘мқҙ м•„лӢҲл©ҙ л№Ҳ к°’мңјлЎң м„Өм •
	if (CurrentStat.ProductionType == EProductionType::None || CurrentStat.ProductionName == NAME_None)
	{
		if (ProducingTxt)
		{
			ProducingTxt->SetText(FText::GetEmpty());
		}
		if (ProducingImg)
		{
			ProducingImg->SetBrushFromTexture(nullptr);
		}
		if (ProducingBar)
		{
			ProducingBar->SetPercent(0.0f);
		}
		return;
	}

	// кұҙл¬ј мғқмӮ° мӨ‘мқё кІҪмҡ°
	if (CurrentStat.ProductionType == EProductionType::Building)
	{
		// кұҙл¬ј лҚ°мқҙн„° к°Җм ёмҳӨкё°
		FBuildingData BuildingData = CachedCityComponent->GetBuildingDataFromTable(CurrentStat.ProductionName);
		
		if (BuildingData.BuildingType != EBuildingType::None)
		{
			// кұҙл¬ј мқҙлҰ„ н‘ңмӢң
			if (ProducingTxt)
			{
				ProducingTxt->SetText(FText::FromString(BuildingData.BuildingName));
			}

			// кұҙл¬ј м•„мқҙмҪҳ н‘ңмӢң
			if (ProducingImg)
			{
				if (!BuildingData.BuildingIcon.IsNull())
				{
					UTexture2D* BuildingIcon = BuildingData.BuildingIcon.LoadSynchronous();
					if (BuildingIcon)
					{
						ProducingImg->SetBrushFromTexture(BuildingIcon);
					}
					else
					{
						ProducingImg->SetBrushFromTexture(nullptr);
					}
				}
				else
				{
					ProducingImg->SetBrushFromTexture(nullptr);
				}
			}

			// кұҙл¬ј м§„н–үлҸ„ л°” м—…лҚ°мқҙнҠё (ProductionProgress / ProductionCost)
			if (ProducingBar)
			{
				float ProgressPercent = 0.0f;
				if (CurrentStat.ProductionCost > 0)
				{
					ProgressPercent = FMath::Clamp((float)CurrentStat.ProductionProgress / (float)CurrentStat.ProductionCost, 0.0f, 1.0f);
				}
				ProducingBar->SetPercent(ProgressPercent);
			}
		}
	}
	// мң лӢӣ мғқмӮ° мӨ‘мқё кІҪмҡ°
	else if (CurrentStat.ProductionType == EProductionType::Unit)
	{
		// мң лӢӣ лҚ°мқҙн„° к°Җм ёмҳӨкё°
		FUnitBaseStat UnitData = CachedCityComponent->GetUnitDataFromTable(CurrentStat.ProductionName);
		
		if (UnitData.UnitClass != EUnitClass::None)
		{
			// мң лӢӣ мқҙлҰ„ н‘ңмӢң
			if (ProducingTxt)
			{
				ProducingTxt->SetText(UnitData.UnitName);
			}

			// мң лӢӣ м•„мқҙмҪҳ н‘ңмӢң
			if (ProducingImg)
			{
				if (!UnitData.UnitIcon.IsNull())
				{
					UTexture2D* UnitIcon = UnitData.UnitIcon.LoadSynchronous();
					if (UnitIcon)
					{
						ProducingImg->SetBrushFromTexture(UnitIcon);
					}
					else
					{
						ProducingImg->SetBrushFromTexture(nullptr);
					}
				}
				else
				{
					ProducingImg->SetBrushFromTexture(nullptr);
				}
			}

			// мң лӢӣ м§„н–үлҸ„ л°” м—…лҚ°мқҙнҠё (FoodProgress / FoodCost)
			if (ProducingBar)
			{
				float ProgressPercent = 0.0f;
				if (CurrentStat.FoodCost > 0)
				{
					ProgressPercent = FMath::Clamp((float)CurrentStat.FoodProgress / (float)CurrentStat.FoodCost, 0.0f, 1.0f);
				}
				ProducingBar->SetPercent(ProgressPercent);
			}
		}
	}
}

